package dev.psiae.mltoolbox.shared.ui.composeui.theme.md3
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

object MD3ColorPalette_Green {
    val primaryLight = Color(0xFF5A631F)
    val onPrimaryLight = Color(0xFFFFFFFF)
    val primaryContainerLight = Color(0xFFDEE995)
    val onPrimaryContainerLight = Color(0xFF191E00)
    val secondaryLight = Color(0xFF5D6145)
    val onSecondaryLight = Color(0xFFFFFFFF)
    val secondaryContainerLight = Color(0xFFE2E5C2)
    val onSecondaryContainerLight = Color(0xFF1A1D07)
    val tertiaryLight = Color(0xFF3B665B)
    val onTertiaryLight = Color(0xFFFFFFFF)
    val tertiaryContainerLight = Color(0xFFBDECDE)
    val onTertiaryContainerLight = Color(0xFF00201A)
    val errorLight = Color(0xFFBA1A1A)
    val onErrorLight = Color(0xFFFFFFFF)
    val errorContainerLight = Color(0xFFFFDAD6)
    val onErrorContainerLight = Color(0xFF410002)
    val backgroundLight = Color(0xFFFCFAED)
    val onBackgroundLight = Color(0xFF1B1C14)
    val surfaceLight = Color(0xFFFCFAED)
    val onSurfaceLight = Color(0xFF1B1C14)
    val surfaceVariantLight = Color(0xFFE4E3D2)
    val onSurfaceVariantLight = Color(0xFF47483B)
    val outlineLight = Color(0xFF77786A)
    val outlineVariantLight = Color(0xFFC8C7B7)
    val scrimLight = Color(0xFF000000)
    val inverseSurfaceLight = Color(0xFF303129)
    val inverseOnSurfaceLight = Color(0xFFF3F1E4)
    val inversePrimaryLight = Color(0xFFC2CD7C)
    val surfaceDimLight = Color(0xFFDCDACE)
    val surfaceBrightLight = Color(0xFFFCFAED)
    val surfaceContainerLowestLight = Color(0xFFFFFFFF)
    val surfaceContainerLowLight = Color(0xFFF6F4E7)
    val surfaceContainerLight = Color(0xFFF0EEE1)
    val surfaceContainerHighLight = Color(0xFFEAE9DC)
    val surfaceContainerHighestLight = Color(0xFFE4E3D6)

    val primaryLightMediumContrast = Color(0xFF3F4702)
    val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
    val primaryContainerLightMediumContrast = Color(0xFF707A33)
    val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    val secondaryLightMediumContrast = Color(0xFF42452B)
    val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
    val secondaryContainerLightMediumContrast = Color(0xFF747759)
    val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    val tertiaryLightMediumContrast = Color(0xFF1E4A40)
    val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
    val tertiaryContainerLightMediumContrast = Color(0xFF517D71)
    val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    val errorLightMediumContrast = Color(0xFF8C0009)
    val onErrorLightMediumContrast = Color(0xFFFFFFFF)
    val errorContainerLightMediumContrast = Color(0xFFDA342E)
    val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
    val backgroundLightMediumContrast = Color(0xFFFCFAED)
    val onBackgroundLightMediumContrast = Color(0xFF1B1C14)
    val surfaceLightMediumContrast = Color(0xFFFCFAED)
    val onSurfaceLightMediumContrast = Color(0xFF1B1C14)
    val surfaceVariantLightMediumContrast = Color(0xFFE4E3D2)
    val onSurfaceVariantLightMediumContrast = Color(0xFF434437)
    val outlineLightMediumContrast = Color(0xFF5F6053)
    val outlineVariantLightMediumContrast = Color(0xFF7B7C6D)
    val scrimLightMediumContrast = Color(0xFF000000)
    val inverseSurfaceLightMediumContrast = Color(0xFF303129)
    val inverseOnSurfaceLightMediumContrast = Color(0xFFF3F1E4)
    val inversePrimaryLightMediumContrast = Color(0xFFC2CD7C)
    val surfaceDimLightMediumContrast = Color(0xFFDCDACE)
    val surfaceBrightLightMediumContrast = Color(0xFFFCFAED)
    val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
    val surfaceContainerLowLightMediumContrast = Color(0xFFF6F4E7)
    val surfaceContainerLightMediumContrast = Color(0xFFF0EEE1)
    val surfaceContainerHighLightMediumContrast = Color(0xFFEAE9DC)
    val surfaceContainerHighestLightMediumContrast = Color(0xFFE4E3D6)

    val primaryLightHighContrast = Color(0xFF202500)
    val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
    val primaryContainerLightHighContrast = Color(0xFF3F4702)
    val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
    val secondaryLightHighContrast = Color(0xFF21240D)
    val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
    val secondaryContainerLightHighContrast = Color(0xFF42452B)
    val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
    val tertiaryLightHighContrast = Color(0xFF002820)
    val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
    val tertiaryContainerLightHighContrast = Color(0xFF1E4A40)
    val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
    val errorLightHighContrast = Color(0xFF4E0002)
    val onErrorLightHighContrast = Color(0xFFFFFFFF)
    val errorContainerLightHighContrast = Color(0xFF8C0009)
    val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
    val backgroundLightHighContrast = Color(0xFFFCFAED)
    val onBackgroundLightHighContrast = Color(0xFF1B1C14)
    val surfaceLightHighContrast = Color(0xFFFCFAED)
    val onSurfaceLightHighContrast = Color(0xFF000000)
    val surfaceVariantLightHighContrast = Color(0xFFE4E3D2)
    val onSurfaceVariantLightHighContrast = Color(0xFF24251A)
    val outlineLightHighContrast = Color(0xFF434437)
    val outlineVariantLightHighContrast = Color(0xFF434437)
    val scrimLightHighContrast = Color(0xFF000000)
    val inverseSurfaceLightHighContrast = Color(0xFF303129)
    val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
    val inversePrimaryLightHighContrast = Color(0xFFE8F39E)
    val surfaceDimLightHighContrast = Color(0xFFDCDACE)
    val surfaceBrightLightHighContrast = Color(0xFFFCFAED)
    val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
    val surfaceContainerLowLightHighContrast = Color(0xFFF6F4E7)
    val surfaceContainerLightHighContrast = Color(0xFFF0EEE1)
    val surfaceContainerHighLightHighContrast = Color(0xFFEAE9DC)
    val surfaceContainerHighestLightHighContrast = Color(0xFFE4E3D6)

    val primaryDark = Color(0xFFC2CD7C)
    val onPrimaryDark = Color(0xFF2D3400)
    val primaryContainerDark = Color(0xFF434B06)
    val onPrimaryContainerDark = Color(0xFFDEE995)
    val secondaryDark = Color(0xFFC6C9A7)
    val onSecondaryDark = Color(0xFF2F321A)
    val secondaryContainerDark = Color(0xFF46492F)
    val onSecondaryContainerDark = Color(0xFFE2E5C2)
    val tertiaryDark = Color(0xFFA2D0C2)
    val onTertiaryDark = Color(0xFF06372E)
    val tertiaryContainerDark = Color(0xFF224E44)
    val onTertiaryContainerDark = Color(0xFFBDECDE)
    val errorDark = Color(0xFFFFB4AB)
    val onErrorDark = Color(0xFF690005)
    val errorContainerDark = Color(0xFF93000A)
    val onErrorContainerDark = Color(0xFFFFDAD6)
    val backgroundDark = Color(0xFF13140D)
    val onBackgroundDark = Color(0xFFE4E3D6)
    val surfaceDark = Color(0xFF13140D)
    val onSurfaceDark = Color(0xFFE4E3D6)
    val surfaceVariantDark = Color(0xFF47483B)
    val onSurfaceVariantDark = Color(0xFFC8C7B7)
    val outlineDark = Color(0xFF919283)
    val outlineVariantDark = Color(0xFF47483B)
    val scrimDark = Color(0xFF000000)
    val inverseSurfaceDark = Color(0xFFE4E3D6)
    val inverseOnSurfaceDark = Color(0xFF303129)
    val inversePrimaryDark = Color(0xFF5A631F)
    val surfaceDimDark = Color(0xFF13140D)
    val surfaceBrightDark = Color(0xFF393A31)
    val surfaceContainerLowestDark = Color(0xFF0E0F08)
    val surfaceContainerLowDark = Color(0xFF1B1C14)
    val surfaceContainerDark = Color(0xFF1F2018)
    val surfaceContainerHighDark = Color(0xFF2A2B22)
    val surfaceContainerHighestDark = Color(0xFF35352D)

    val primaryDarkMediumContrast = Color(0xFFC6D180)
    val onPrimaryDarkMediumContrast = Color(0xFF141800)
    val primaryContainerDarkMediumContrast = Color(0xFF8C974C)
    val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
    val secondaryDarkMediumContrast = Color(0xFFCACDAB)
    val onSecondaryDarkMediumContrast = Color(0xFF151804)
    val secondaryContainerDarkMediumContrast = Color(0xFF909374)
    val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
    val tertiaryDarkMediumContrast = Color(0xFFA6D4C6)
    val onTertiaryDarkMediumContrast = Color(0xFF001A15)
    val tertiaryContainerDarkMediumContrast = Color(0xFF6D9A8D)
    val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
    val errorDarkMediumContrast = Color(0xFFFFBAB1)
    val onErrorDarkMediumContrast = Color(0xFF370001)
    val errorContainerDarkMediumContrast = Color(0xFFFF5449)
    val onErrorContainerDarkMediumContrast = Color(0xFF000000)
    val backgroundDarkMediumContrast = Color(0xFF13140D)
    val onBackgroundDarkMediumContrast = Color(0xFFE4E3D6)
    val surfaceDarkMediumContrast = Color(0xFF13140D)
    val onSurfaceDarkMediumContrast = Color(0xFFFDFBEE)
    val surfaceVariantDarkMediumContrast = Color(0xFF47483B)
    val onSurfaceVariantDarkMediumContrast = Color(0xFFCCCCBB)
    val outlineDarkMediumContrast = Color(0xFFA4A494)
    val outlineVariantDarkMediumContrast = Color(0xFF848475)
    val scrimDarkMediumContrast = Color(0xFF000000)
    val inverseSurfaceDarkMediumContrast = Color(0xFFE4E3D6)
    val inverseOnSurfaceDarkMediumContrast = Color(0xFF2A2B22)
    val inversePrimaryDarkMediumContrast = Color(0xFF444C07)
    val surfaceDimDarkMediumContrast = Color(0xFF13140D)
    val surfaceBrightDarkMediumContrast = Color(0xFF393A31)
    val surfaceContainerLowestDarkMediumContrast = Color(0xFF0E0F08)
    val surfaceContainerLowDarkMediumContrast = Color(0xFF1B1C14)
    val surfaceContainerDarkMediumContrast = Color(0xFF1F2018)
    val surfaceContainerHighDarkMediumContrast = Color(0xFF2A2B22)
    val surfaceContainerHighestDarkMediumContrast = Color(0xFF35352D)

    val primaryDarkHighContrast = Color(0xFFFAFFCB)
    val onPrimaryDarkHighContrast = Color(0xFF000000)
    val primaryContainerDarkHighContrast = Color(0xFFC6D180)
    val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
    val secondaryDarkHighContrast = Color(0xFFFBFED9)
    val onSecondaryDarkHighContrast = Color(0xFF000000)
    val secondaryContainerDarkHighContrast = Color(0xFFCACDAB)
    val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
    val tertiaryDarkHighContrast = Color(0xFFECFFF7)
    val onTertiaryDarkHighContrast = Color(0xFF000000)
    val tertiaryContainerDarkHighContrast = Color(0xFFA6D4C6)
    val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
    val errorDarkHighContrast = Color(0xFFFFF9F9)
    val onErrorDarkHighContrast = Color(0xFF000000)
    val errorContainerDarkHighContrast = Color(0xFFFFBAB1)
    val onErrorContainerDarkHighContrast = Color(0xFF000000)
    val backgroundDarkHighContrast = Color(0xFF13140D)
    val onBackgroundDarkHighContrast = Color(0xFFE4E3D6)
    val surfaceDarkHighContrast = Color(0xFF13140D)
    val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
    val surfaceVariantDarkHighContrast = Color(0xFF47483B)
    val onSurfaceVariantDarkHighContrast = Color(0xFFFDFCEA)
    val outlineDarkHighContrast = Color(0xFFCCCCBB)
    val outlineVariantDarkHighContrast = Color(0xFFCCCCBB)
    val scrimDarkHighContrast = Color(0xFF000000)
    val inverseSurfaceDarkHighContrast = Color(0xFFE4E3D6)
    val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
    val inversePrimaryDarkHighContrast = Color(0xFF272D00)
    val surfaceDimDarkHighContrast = Color(0xFF13140D)
    val surfaceBrightDarkHighContrast = Color(0xFF393A31)
    val surfaceContainerLowestDarkHighContrast = Color(0xFF0E0F08)
    val surfaceContainerLowDarkHighContrast = Color(0xFF1B1C14)
    val surfaceContainerDarkHighContrast = Color(0xFF1F2018)
    val surfaceContainerHighDarkHighContrast = Color(0xFF2A2B22)
    val surfaceContainerHighestDarkHighContrast = Color(0xFF35352D)

    val lightColorScheme = lightColorScheme(
        primary = primaryLight,
        onPrimary = onPrimaryLight,
        primaryContainer = primaryContainerLight,
        onPrimaryContainer = onPrimaryContainerLight,
        secondary = secondaryLight,
        onSecondary = onSecondaryLight,
        secondaryContainer = secondaryContainerLight,
        onSecondaryContainer = onSecondaryContainerLight,
        tertiary = tertiaryLight,
        onTertiary = onTertiaryLight,
        tertiaryContainer = tertiaryContainerLight,
        onTertiaryContainer = onTertiaryContainerLight,
        error = errorLight,
        onError = onErrorLight,
        errorContainer = errorContainerLight,
        onErrorContainer = onErrorContainerLight,
        background = backgroundLight,
        onBackground = onBackgroundLight,
        surface = surfaceLight,
        onSurface = onSurfaceLight,
        surfaceVariant = surfaceVariantLight,
        onSurfaceVariant = onSurfaceVariantLight,
        outline = outlineLight,
        outlineVariant = outlineVariantLight,
        scrim = scrimLight,
        inverseSurface = inverseSurfaceLight,
        inverseOnSurface = inverseOnSurfaceLight,
        inversePrimary = inversePrimaryLight,
        surfaceDim = surfaceDimLight,
        surfaceBright = surfaceBrightLight,
        surfaceContainerLowest = surfaceContainerLowestLight,
        surfaceContainerLow = surfaceContainerLowLight,
        surfaceContainer = surfaceContainerLight,
        surfaceContainerHigh = surfaceContainerHighLight,
        surfaceContainerHighest = surfaceContainerHighestLight
    )

    val darkColorScheme = darkColorScheme(
        primary = primaryDark,
        onPrimary = onPrimaryDark,
        primaryContainer = primaryContainerDark,
        onPrimaryContainer = onPrimaryContainerDark,
        secondary = secondaryDark,
        onSecondary = onSecondaryDark,
        secondaryContainer = secondaryContainerDark,
        onSecondaryContainer = onSecondaryContainerDark,
        tertiary = tertiaryDark,
        onTertiary = onTertiaryDark,
        tertiaryContainer = tertiaryContainerDark,
        onTertiaryContainer = onTertiaryContainerDark,
        error = errorDark,
        onError = onErrorDark,
        errorContainer = errorContainerDark,
        onErrorContainer = onErrorContainerDark,
        background = backgroundDark,
        onBackground = onBackgroundDark,
        surface = surfaceDark,
        onSurface = onSurfaceDark,
        surfaceVariant = surfaceVariantDark,
        onSurfaceVariant = onSurfaceVariantDark,
        outline = outlineDark,
        outlineVariant = outlineVariantDark,
        scrim = scrimDark,
        inverseSurface = inverseSurfaceDark,
        inverseOnSurface = inverseOnSurfaceDark,
        inversePrimary = inversePrimaryDark,
        surfaceDim = surfaceDimDark,
        surfaceBright = surfaceBrightDark,
        surfaceContainerLowest = surfaceContainerLowestDark,
        surfaceContainerLow = surfaceContainerLowDark,
        surfaceContainer = surfaceContainerDark,
        surfaceContainerHigh = surfaceContainerHighDark,
        surfaceContainerHighest = surfaceContainerHighestDark,
    )
}

object MD3ColorPalette_Orange {
    val primaryLight = Color(0xFF8F4C38)
    val onPrimaryLight = Color(0xFFFFFFFF)
    val primaryContainerLight = Color(0xFFFFDBD1)
    val onPrimaryContainerLight = Color(0xFF723523)
    val secondaryLight = Color(0xFF77574E)
    val onSecondaryLight = Color(0xFFFFFFFF)
    val secondaryContainerLight = Color(0xFFFFDBD1)
    val onSecondaryContainerLight = Color(0xFF5D4037)
    val tertiaryLight = Color(0xFF6C5D2F)
    val onTertiaryLight = Color(0xFFFFFFFF)
    val tertiaryContainerLight = Color(0xFFF5E1A7)
    val onTertiaryContainerLight = Color(0xFF534619)
    val errorLight = Color(0xFFBA1A1A)
    val onErrorLight = Color(0xFFFFFFFF)
    val errorContainerLight = Color(0xFFFFDAD6)
    val onErrorContainerLight = Color(0xFF93000A)
    val backgroundLight = Color(0xFFFFF8F6)
    val onBackgroundLight = Color(0xFF231917)
    val surfaceLight = Color(0xFFFFF8F6)
    val onSurfaceLight = Color(0xFF231917)
    val surfaceVariantLight = Color(0xFFF5DED8)
    val onSurfaceVariantLight = Color(0xFF53433F)
    val outlineLight = Color(0xFF85736E)
    val outlineVariantLight = Color(0xFFD8C2BC)
    val scrimLight = Color(0xFF000000)
    val inverseSurfaceLight = Color(0xFF392E2B)
    val inverseOnSurfaceLight = Color(0xFFFFEDE8)
    val inversePrimaryLight = Color(0xFFFFB5A0)
    val surfaceDimLight = Color(0xFFE8D6D2)
    val surfaceBrightLight = Color(0xFFFFF8F6)
    val surfaceContainerLowestLight = Color(0xFFFFFFFF)
    val surfaceContainerLowLight = Color(0xFFFFF1ED)
    val surfaceContainerLight = Color(0xFFFCEAE5)
    val surfaceContainerHighLight = Color(0xFFF7E4E0)
    val surfaceContainerHighestLight = Color(0xFFF1DFDA)

    val primaryLightMediumContrast = Color(0xFF5D2514)
    val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
    val primaryContainerLightMediumContrast = Color(0xFFA15A45)
    val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    val secondaryLightMediumContrast = Color(0xFF4B2F28)
    val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
    val secondaryContainerLightMediumContrast = Color(0xFF87655C)
    val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    val tertiaryLightMediumContrast = Color(0xFF41350A)
    val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
    val tertiaryContainerLightMediumContrast = Color(0xFF7B6C3C)
    val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    val errorLightMediumContrast = Color(0xFF740006)
    val onErrorLightMediumContrast = Color(0xFFFFFFFF)
    val errorContainerLightMediumContrast = Color(0xFFCF2C27)
    val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
    val backgroundLightMediumContrast = Color(0xFFFFF8F6)
    val onBackgroundLightMediumContrast = Color(0xFF231917)
    val surfaceLightMediumContrast = Color(0xFFFFF8F6)
    val onSurfaceLightMediumContrast = Color(0xFF180F0D)
    val surfaceVariantLightMediumContrast = Color(0xFFF5DED8)
    val onSurfaceVariantLightMediumContrast = Color(0xFF41332F)
    val outlineLightMediumContrast = Color(0xFF5F4F4A)
    val outlineVariantLightMediumContrast = Color(0xFF7B6964)
    val scrimLightMediumContrast = Color(0xFF000000)
    val inverseSurfaceLightMediumContrast = Color(0xFF392E2B)
    val inverseOnSurfaceLightMediumContrast = Color(0xFFFFEDE8)
    val inversePrimaryLightMediumContrast = Color(0xFFFFB5A0)
    val surfaceDimLightMediumContrast = Color(0xFFD4C3BE)
    val surfaceBrightLightMediumContrast = Color(0xFFFFF8F6)
    val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
    val surfaceContainerLowLightMediumContrast = Color(0xFFFFF1ED)
    val surfaceContainerLightMediumContrast = Color(0xFFF7E4E0)
    val surfaceContainerHighLightMediumContrast = Color(0xFFEBD9D4)
    val surfaceContainerHighestLightMediumContrast = Color(0xFFDFCEC9)

    val primaryLightHighContrast = Color(0xFF501B0B)
    val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
    val primaryContainerLightHighContrast = Color(0xFF753725)
    val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
    val secondaryLightHighContrast = Color(0xFF3F261E)
    val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
    val secondaryContainerLightHighContrast = Color(0xFF60423A)
    val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
    val tertiaryLightHighContrast = Color(0xFF362B02)
    val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
    val tertiaryContainerLightHighContrast = Color(0xFF55481C)
    val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
    val errorLightHighContrast = Color(0xFF600004)
    val onErrorLightHighContrast = Color(0xFFFFFFFF)
    val errorContainerLightHighContrast = Color(0xFF98000A)
    val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
    val backgroundLightHighContrast = Color(0xFFFFF8F6)
    val onBackgroundLightHighContrast = Color(0xFF231917)
    val surfaceLightHighContrast = Color(0xFFFFF8F6)
    val onSurfaceLightHighContrast = Color(0xFF000000)
    val surfaceVariantLightHighContrast = Color(0xFFF5DED8)
    val onSurfaceVariantLightHighContrast = Color(0xFF000000)
    val outlineLightHighContrast = Color(0xFF372925)
    val outlineVariantLightHighContrast = Color(0xFF554641)
    val scrimLightHighContrast = Color(0xFF000000)
    val inverseSurfaceLightHighContrast = Color(0xFF392E2B)
    val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
    val inversePrimaryLightHighContrast = Color(0xFFFFB5A0)
    val surfaceDimLightHighContrast = Color(0xFFC6B5B1)
    val surfaceBrightLightHighContrast = Color(0xFFFFF8F6)
    val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
    val surfaceContainerLowLightHighContrast = Color(0xFFFFEDE8)
    val surfaceContainerLightHighContrast = Color(0xFFF1DFDA)
    val surfaceContainerHighLightHighContrast = Color(0xFFE2D1CC)
    val surfaceContainerHighestLightHighContrast = Color(0xFFD4C3BE)

    val primaryDark = Color(0xFFFFB5A0)
    val onPrimaryDark = Color(0xFF561F0F)
    val primaryContainerDark = Color(0xFF723523)
    val onPrimaryContainerDark = Color(0xFFFFDBD1)
    val secondaryDark = Color(0xFFE7BDB2)
    val onSecondaryDark = Color(0xFF442A22)
    val secondaryContainerDark = Color(0xFF5D4037)
    val onSecondaryContainerDark = Color(0xFFFFDBD1)
    val tertiaryDark = Color(0xFFD8C58D)
    val onTertiaryDark = Color(0xFF3B2F05)
    val tertiaryContainerDark = Color(0xFF534619)
    val onTertiaryContainerDark = Color(0xFFF5E1A7)
    val errorDark = Color(0xFFFFB4AB)
    val onErrorDark = Color(0xFF690005)
    val errorContainerDark = Color(0xFF93000A)
    val onErrorContainerDark = Color(0xFFFFDAD6)
    val backgroundDark = Color(0xFF1A110F)
    val onBackgroundDark = Color(0xFFF1DFDA)
    val surfaceDark = Color(0xFF1A110F)
    val onSurfaceDark = Color(0xFFF1DFDA)
    val surfaceVariantDark = Color(0xFF53433F)
    val onSurfaceVariantDark = Color(0xFFD8C2BC)
    val outlineDark = Color(0xFFA08C87)
    val outlineVariantDark = Color(0xFF53433F)
    val scrimDark = Color(0xFF000000)
    val inverseSurfaceDark = Color(0xFFF1DFDA)
    val inverseOnSurfaceDark = Color(0xFF392E2B)
    val inversePrimaryDark = Color(0xFF8F4C38)
    val surfaceDimDark = Color(0xFF1A110F)
    val surfaceBrightDark = Color(0xFF423734)
    val surfaceContainerLowestDark = Color(0xFF140C0A)
    val surfaceContainerLowDark = Color(0xFF231917)
    val surfaceContainerDark = Color(0xFF271D1B)
    val surfaceContainerHighDark = Color(0xFF322825)
    val surfaceContainerHighestDark = Color(0xFF3D322F)

    val primaryDarkMediumContrast = Color(0xFFFFD2C6)
    val onPrimaryDarkMediumContrast = Color(0xFF481506)
    val primaryContainerDarkMediumContrast = Color(0xFFCB7C65)
    val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
    val secondaryDarkMediumContrast = Color(0xFFFED3C7)
    val onSecondaryDarkMediumContrast = Color(0xFF381F18)
    val secondaryContainerDarkMediumContrast = Color(0xFFAE887E)
    val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
    val tertiaryDarkMediumContrast = Color(0xFFEFDBA1)
    val onTertiaryDarkMediumContrast = Color(0xFF2F2500)
    val tertiaryContainerDarkMediumContrast = Color(0xFFA0905C)
    val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
    val errorDarkMediumContrast = Color(0xFFFFD2CC)
    val onErrorDarkMediumContrast = Color(0xFF540003)
    val errorContainerDarkMediumContrast = Color(0xFFFF5449)
    val onErrorContainerDarkMediumContrast = Color(0xFF000000)
    val backgroundDarkMediumContrast = Color(0xFF1A110F)
    val onBackgroundDarkMediumContrast = Color(0xFFF1DFDA)
    val surfaceDarkMediumContrast = Color(0xFF1A110F)
    val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
    val surfaceVariantDarkMediumContrast = Color(0xFF53433F)
    val onSurfaceVariantDarkMediumContrast = Color(0xFFEED7D1)
    val outlineDarkMediumContrast = Color(0xFFC2ADA8)
    val outlineVariantDarkMediumContrast = Color(0xFFA08C87)
    val scrimDarkMediumContrast = Color(0xFF000000)
    val inverseSurfaceDarkMediumContrast = Color(0xFFF1DFDA)
    val inverseOnSurfaceDarkMediumContrast = Color(0xFF322825)
    val inversePrimaryDarkMediumContrast = Color(0xFF743624)
    val surfaceDimDarkMediumContrast = Color(0xFF1A110F)
    val surfaceBrightDarkMediumContrast = Color(0xFF4E423F)
    val surfaceContainerLowestDarkMediumContrast = Color(0xFF0D0604)
    val surfaceContainerLowDarkMediumContrast = Color(0xFF251B19)
    val surfaceContainerDarkMediumContrast = Color(0xFF302623)
    val surfaceContainerHighDarkMediumContrast = Color(0xFF3B302D)
    val surfaceContainerHighestDarkMediumContrast = Color(0xFF463B38)

    val primaryDarkHighContrast = Color(0xFFFFECE7)
    val onPrimaryDarkHighContrast = Color(0xFF000000)
    val primaryContainerDarkHighContrast = Color(0xFFFFAF98)
    val onPrimaryContainerDarkHighContrast = Color(0xFF1E0300)
    val secondaryDarkHighContrast = Color(0xFFFFECE7)
    val onSecondaryDarkHighContrast = Color(0xFF000000)
    val secondaryContainerDarkHighContrast = Color(0xFFE3B9AE)
    val onSecondaryContainerDarkHighContrast = Color(0xFF190603)
    val tertiaryDarkHighContrast = Color(0xFFFFEFC4)
    val onTertiaryDarkHighContrast = Color(0xFF000000)
    val tertiaryContainerDarkHighContrast = Color(0xFFD4C289)
    val onTertiaryContainerDarkHighContrast = Color(0xFF100B00)
    val errorDarkHighContrast = Color(0xFFFFECE9)
    val onErrorDarkHighContrast = Color(0xFF000000)
    val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
    val onErrorContainerDarkHighContrast = Color(0xFF220001)
    val backgroundDarkHighContrast = Color(0xFF1A110F)
    val onBackgroundDarkHighContrast = Color(0xFFF1DFDA)
    val surfaceDarkHighContrast = Color(0xFF1A110F)
    val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
    val surfaceVariantDarkHighContrast = Color(0xFF53433F)
    val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
    val outlineDarkHighContrast = Color(0xFFFFECE7)
    val outlineVariantDarkHighContrast = Color(0xFFD4BEB8)
    val scrimDarkHighContrast = Color(0xFF000000)
    val inverseSurfaceDarkHighContrast = Color(0xFFF1DFDA)
    val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
    val inversePrimaryDarkHighContrast = Color(0xFF743624)
    val surfaceDimDarkHighContrast = Color(0xFF1A110F)
    val surfaceBrightDarkHighContrast = Color(0xFF5A4D4A)
    val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
    val surfaceContainerLowDarkHighContrast = Color(0xFF271D1B)
    val surfaceContainerDarkHighContrast = Color(0xFF392E2B)
    val surfaceContainerHighDarkHighContrast = Color(0xFF443936)
    val surfaceContainerHighestDarkHighContrast = Color(0xFF504441)

    val lightColorScheme = lightColorScheme(
        primary = primaryLight,
        onPrimary = onPrimaryLight,
        primaryContainer = primaryContainerLight,
        onPrimaryContainer = onPrimaryContainerLight,
        secondary = secondaryLight,
        onSecondary = onSecondaryLight,
        secondaryContainer = secondaryContainerLight,
        onSecondaryContainer = onSecondaryContainerLight,
        tertiary = tertiaryLight,
        onTertiary = onTertiaryLight,
        tertiaryContainer = tertiaryContainerLight,
        onTertiaryContainer = onTertiaryContainerLight,
        error = errorLight,
        onError = onErrorLight,
        errorContainer = errorContainerLight,
        onErrorContainer = onErrorContainerLight,
        background = backgroundLight,
        onBackground = onBackgroundLight,
        surface = surfaceLight,
        onSurface = onSurfaceLight,
        surfaceVariant = surfaceVariantLight,
        onSurfaceVariant = onSurfaceVariantLight,
        outline = outlineLight,
        outlineVariant = outlineVariantLight,
        scrim = scrimLight,
        inverseSurface = inverseSurfaceLight,
        inverseOnSurface = inverseOnSurfaceLight,
        inversePrimary = inversePrimaryLight,
        surfaceDim = surfaceDimLight,
        surfaceBright = surfaceBrightLight,
        surfaceContainerLowest = surfaceContainerLowestLight,
        surfaceContainerLow = surfaceContainerLowLight,
        surfaceContainer = surfaceContainerLight,
        surfaceContainerHigh = surfaceContainerHighLight,
        surfaceContainerHighest = surfaceContainerHighestLight
    )

    val darkColorScheme = darkColorScheme(
        primary = primaryDark,
        onPrimary = onPrimaryDark,
        primaryContainer = primaryContainerDark,
        onPrimaryContainer = onPrimaryContainerDark,
        secondary = secondaryDark,
        onSecondary = onSecondaryDark,
        secondaryContainer = secondaryContainerDark,
        onSecondaryContainer = onSecondaryContainerDark,
        tertiary = tertiaryDark,
        onTertiary = onTertiaryDark,
        tertiaryContainer = tertiaryContainerDark,
        onTertiaryContainer = onTertiaryContainerDark,
        error = errorDark,
        onError = onErrorDark,
        errorContainer = errorContainerDark,
        onErrorContainer = onErrorContainerDark,
        background = backgroundDark,
        onBackground = onBackgroundDark,
        surface = surfaceDark,
        onSurface = onSurfaceDark,
        surfaceVariant = surfaceVariantDark,
        onSurfaceVariant = onSurfaceVariantDark,
        outline = outlineDark,
        outlineVariant = outlineVariantDark,
        scrim = scrimDark,
        inverseSurface = inverseSurfaceDark,
        inverseOnSurface = inverseOnSurfaceDark,
        inversePrimary = inversePrimaryDark,
        surfaceDim = surfaceDimDark,
        surfaceBright = surfaceBrightDark,
        surfaceContainerLowest = surfaceContainerLowestDark,
        surfaceContainerLow = surfaceContainerLowDark,
        surfaceContainer = surfaceContainerDark,
        surfaceContainerHigh = surfaceContainerHighDark,
        surfaceContainerHighest = surfaceContainerHighestDark,
    )
}

object MD3ColorPalette_Blue {
    val primaryLight = Color(0xFF415F91)
    val onPrimaryLight = Color(0xFFFFFFFF)
    val primaryContainerLight = Color(0xFFD6E3FF)
    val onPrimaryContainerLight = Color(0xFF284777)
    val secondaryLight = Color(0xFF565F71)
    val onSecondaryLight = Color(0xFFFFFFFF)
    val secondaryContainerLight = Color(0xFFDAE2F9)
    val onSecondaryContainerLight = Color(0xFF3E4759)
    val tertiaryLight = Color(0xFF705575)
    val onTertiaryLight = Color(0xFFFFFFFF)
    val tertiaryContainerLight = Color(0xFFFAD8FD)
    val onTertiaryContainerLight = Color(0xFF573E5C)
    val errorLight = Color(0xFFBA1A1A)
    val onErrorLight = Color(0xFFFFFFFF)
    val errorContainerLight = Color(0xFFFFDAD6)
    val onErrorContainerLight = Color(0xFF93000A)
    val backgroundLight = Color(0xFFF9F9FF)
    val onBackgroundLight = Color(0xFF191C20)
    val surfaceLight = Color(0xFFF9F9FF)
    val onSurfaceLight = Color(0xFF191C20)
    val surfaceVariantLight = Color(0xFFE0E2EC)
    val onSurfaceVariantLight = Color(0xFF44474E)
    val outlineLight = Color(0xFF74777F)
    val outlineVariantLight = Color(0xFFC4C6D0)
    val scrimLight = Color(0xFF000000)
    val inverseSurfaceLight = Color(0xFF2E3036)
    val inverseOnSurfaceLight = Color(0xFFF0F0F7)
    val inversePrimaryLight = Color(0xFFAAC7FF)
    val surfaceDimLight = Color(0xFFD9D9E0)
    val surfaceBrightLight = Color(0xFFF9F9FF)
    val surfaceContainerLowestLight = Color(0xFFFFFFFF)
    val surfaceContainerLowLight = Color(0xFFF3F3FA)
    val surfaceContainerLight = Color(0xFFEDEDF4)
    val surfaceContainerHighLight = Color(0xFFE7E8EE)
    val surfaceContainerHighestLight = Color(0xFFE2E2E9)

    val primaryLightMediumContrast = Color(0xFF133665)
    val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
    val primaryContainerLightMediumContrast = Color(0xFF506DA0)
    val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    val secondaryLightMediumContrast = Color(0xFF2E3647)
    val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
    val secondaryContainerLightMediumContrast = Color(0xFF646D80)
    val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    val tertiaryLightMediumContrast = Color(0xFF452E4A)
    val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
    val tertiaryContainerLightMediumContrast = Color(0xFF7F6484)
    val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    val errorLightMediumContrast = Color(0xFF740006)
    val onErrorLightMediumContrast = Color(0xFFFFFFFF)
    val errorContainerLightMediumContrast = Color(0xFFCF2C27)
    val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
    val backgroundLightMediumContrast = Color(0xFFF9F9FF)
    val onBackgroundLightMediumContrast = Color(0xFF191C20)
    val surfaceLightMediumContrast = Color(0xFFF9F9FF)
    val onSurfaceLightMediumContrast = Color(0xFF0F1116)
    val surfaceVariantLightMediumContrast = Color(0xFFE0E2EC)
    val onSurfaceVariantLightMediumContrast = Color(0xFF33363E)
    val outlineLightMediumContrast = Color(0xFF4F525A)
    val outlineVariantLightMediumContrast = Color(0xFF6A6D75)
    val scrimLightMediumContrast = Color(0xFF000000)
    val inverseSurfaceLightMediumContrast = Color(0xFF2E3036)
    val inverseOnSurfaceLightMediumContrast = Color(0xFFF0F0F7)
    val inversePrimaryLightMediumContrast = Color(0xFFAAC7FF)
    val surfaceDimLightMediumContrast = Color(0xFFC5C6CD)
    val surfaceBrightLightMediumContrast = Color(0xFFF9F9FF)
    val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
    val surfaceContainerLowLightMediumContrast = Color(0xFFF3F3FA)
    val surfaceContainerLightMediumContrast = Color(0xFFE7E8EE)
    val surfaceContainerHighLightMediumContrast = Color(0xFFDCDCE3)
    val surfaceContainerHighestLightMediumContrast = Color(0xFFD1D1D8)

    val primaryLightHighContrast = Color(0xFF032B5B)
    val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
    val primaryContainerLightHighContrast = Color(0xFF2A497A)
    val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
    val secondaryLightHighContrast = Color(0xFF232C3D)
    val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
    val secondaryContainerLightHighContrast = Color(0xFF41495B)
    val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
    val tertiaryLightHighContrast = Color(0xFF3A2440)
    val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
    val tertiaryContainerLightHighContrast = Color(0xFF59405E)
    val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
    val errorLightHighContrast = Color(0xFF600004)
    val onErrorLightHighContrast = Color(0xFFFFFFFF)
    val errorContainerLightHighContrast = Color(0xFF98000A)
    val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
    val backgroundLightHighContrast = Color(0xFFF9F9FF)
    val onBackgroundLightHighContrast = Color(0xFF191C20)
    val surfaceLightHighContrast = Color(0xFFF9F9FF)
    val onSurfaceLightHighContrast = Color(0xFF000000)
    val surfaceVariantLightHighContrast = Color(0xFFE0E2EC)
    val onSurfaceVariantLightHighContrast = Color(0xFF000000)
    val outlineLightHighContrast = Color(0xFF292C33)
    val outlineVariantLightHighContrast = Color(0xFF464951)
    val scrimLightHighContrast = Color(0xFF000000)
    val inverseSurfaceLightHighContrast = Color(0xFF2E3036)
    val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
    val inversePrimaryLightHighContrast = Color(0xFFAAC7FF)
    val surfaceDimLightHighContrast = Color(0xFFB8B8BF)
    val surfaceBrightLightHighContrast = Color(0xFFF9F9FF)
    val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
    val surfaceContainerLowLightHighContrast = Color(0xFFF0F0F7)
    val surfaceContainerLightHighContrast = Color(0xFFE2E2E9)
    val surfaceContainerHighLightHighContrast = Color(0xFFD3D4DB)
    val surfaceContainerHighestLightHighContrast = Color(0xFFC5C6CD)

    val primaryDark = Color(0xFFAAC7FF)
    val onPrimaryDark = Color(0xFF0A305F)
    val primaryContainerDark = Color(0xFF284777)
    val onPrimaryContainerDark = Color(0xFFD6E3FF)
    val secondaryDark = Color(0xFFBEC6DC)
    val onSecondaryDark = Color(0xFF283141)
    val secondaryContainerDark = Color(0xFF3E4759)
    val onSecondaryContainerDark = Color(0xFFDAE2F9)
    val tertiaryDark = Color(0xFFDDBCE0)
    val onTertiaryDark = Color(0xFF3F2844)
    val tertiaryContainerDark = Color(0xFF573E5C)
    val onTertiaryContainerDark = Color(0xFFFAD8FD)
    val errorDark = Color(0xFFFFB4AB)
    val onErrorDark = Color(0xFF690005)
    val errorContainerDark = Color(0xFF93000A)
    val onErrorContainerDark = Color(0xFFFFDAD6)
    val backgroundDark = Color(0xFF111318)
    val onBackgroundDark = Color(0xFFE2E2E9)
    val surfaceDark = Color(0xFF111318)
    val onSurfaceDark = Color(0xFFE2E2E9)
    val surfaceVariantDark = Color(0xFF44474E)
    val onSurfaceVariantDark = Color(0xFFC4C6D0)
    val outlineDark = Color(0xFF8E9099)
    val outlineVariantDark = Color(0xFF44474E)
    val scrimDark = Color(0xFF000000)
    val inverseSurfaceDark = Color(0xFFE2E2E9)
    val inverseOnSurfaceDark = Color(0xFF2E3036)
    val inversePrimaryDark = Color(0xFF415F91)
    val surfaceDimDark = Color(0xFF111318)
    val surfaceBrightDark = Color(0xFF37393E)
    val surfaceContainerLowestDark = Color(0xFF0C0E13)
    val surfaceContainerLowDark = Color(0xFF191C20)
    val surfaceContainerDark = Color(0xFF1D2024)
    val surfaceContainerHighDark = Color(0xFF282A2F)
    val surfaceContainerHighestDark = Color(0xFF33353A)

    val primaryDarkMediumContrast = Color(0xFFCDDDFF)
    val onPrimaryDarkMediumContrast = Color(0xFF002551)
    val primaryContainerDarkMediumContrast = Color(0xFF7491C7)
    val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
    val secondaryDarkMediumContrast = Color(0xFFD4DCF2)
    val onSecondaryDarkMediumContrast = Color(0xFF1D2636)
    val secondaryContainerDarkMediumContrast = Color(0xFF8891A5)
    val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
    val tertiaryDarkMediumContrast = Color(0xFFF3D2F7)
    val onTertiaryDarkMediumContrast = Color(0xFF331D39)
    val tertiaryContainerDarkMediumContrast = Color(0xFFA487A9)
    val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
    val errorDarkMediumContrast = Color(0xFFFFD2CC)
    val onErrorDarkMediumContrast = Color(0xFF540003)
    val errorContainerDarkMediumContrast = Color(0xFFFF5449)
    val onErrorContainerDarkMediumContrast = Color(0xFF000000)
    val backgroundDarkMediumContrast = Color(0xFF111318)
    val onBackgroundDarkMediumContrast = Color(0xFFE2E2E9)
    val surfaceDarkMediumContrast = Color(0xFF111318)
    val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
    val surfaceVariantDarkMediumContrast = Color(0xFF44474E)
    val onSurfaceVariantDarkMediumContrast = Color(0xFFDADCE6)
    val outlineDarkMediumContrast = Color(0xFFAFB2BB)
    val outlineVariantDarkMediumContrast = Color(0xFF8E9099)
    val scrimDarkMediumContrast = Color(0xFF000000)
    val inverseSurfaceDarkMediumContrast = Color(0xFFE2E2E9)
    val inverseOnSurfaceDarkMediumContrast = Color(0xFF282A2F)
    val inversePrimaryDarkMediumContrast = Color(0xFF294878)
    val surfaceDimDarkMediumContrast = Color(0xFF111318)
    val surfaceBrightDarkMediumContrast = Color(0xFF43444A)
    val surfaceContainerLowestDarkMediumContrast = Color(0xFF06070C)
    val surfaceContainerLowDarkMediumContrast = Color(0xFF1B1E22)
    val surfaceContainerDarkMediumContrast = Color(0xFF26282D)
    val surfaceContainerHighDarkMediumContrast = Color(0xFF313238)
    val surfaceContainerHighestDarkMediumContrast = Color(0xFF3C3E43)

    val primaryDarkHighContrast = Color(0xFFEBF0FF)
    val onPrimaryDarkHighContrast = Color(0xFF000000)
    val primaryContainerDarkHighContrast = Color(0xFFA6C3FC)
    val onPrimaryContainerDarkHighContrast = Color(0xFF000B20)
    val secondaryDarkHighContrast = Color(0xFFEBF0FF)
    val onSecondaryDarkHighContrast = Color(0xFF000000)
    val secondaryContainerDarkHighContrast = Color(0xFFBAC3D8)
    val onSecondaryContainerDarkHighContrast = Color(0xFF030B1A)
    val tertiaryDarkHighContrast = Color(0xFFFFE9FF)
    val onTertiaryDarkHighContrast = Color(0xFF000000)
    val tertiaryContainerDarkHighContrast = Color(0xFFD8B8DC)
    val onTertiaryContainerDarkHighContrast = Color(0xFF16041D)
    val errorDarkHighContrast = Color(0xFFFFECE9)
    val onErrorDarkHighContrast = Color(0xFF000000)
    val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
    val onErrorContainerDarkHighContrast = Color(0xFF220001)
    val backgroundDarkHighContrast = Color(0xFF111318)
    val onBackgroundDarkHighContrast = Color(0xFFE2E2E9)
    val surfaceDarkHighContrast = Color(0xFF111318)
    val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
    val surfaceVariantDarkHighContrast = Color(0xFF44474E)
    val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
    val outlineDarkHighContrast = Color(0xFFEEEFF9)
    val outlineVariantDarkHighContrast = Color(0xFFC0C2CC)
    val scrimDarkHighContrast = Color(0xFF000000)
    val inverseSurfaceDarkHighContrast = Color(0xFFE2E2E9)
    val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
    val inversePrimaryDarkHighContrast = Color(0xFF294878)
    val surfaceDimDarkHighContrast = Color(0xFF111318)
    val surfaceBrightDarkHighContrast = Color(0xFF4E5056)
    val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
    val surfaceContainerLowDarkHighContrast = Color(0xFF1D2024)
    val surfaceContainerDarkHighContrast = Color(0xFF2E3036)
    val surfaceContainerHighDarkHighContrast = Color(0xFF393B41)
    val surfaceContainerHighestDarkHighContrast = Color(0xFF45474C)

    val lightColorScheme = lightColorScheme(
        primary = primaryLight,
        onPrimary = onPrimaryLight,
        primaryContainer = primaryContainerLight,
        onPrimaryContainer = onPrimaryContainerLight,
        secondary = secondaryLight,
        onSecondary = onSecondaryLight,
        secondaryContainer = secondaryContainerLight,
        onSecondaryContainer = onSecondaryContainerLight,
        tertiary = tertiaryLight,
        onTertiary = onTertiaryLight,
        tertiaryContainer = tertiaryContainerLight,
        onTertiaryContainer = onTertiaryContainerLight,
        error = errorLight,
        onError = onErrorLight,
        errorContainer = errorContainerLight,
        onErrorContainer = onErrorContainerLight,
        background = backgroundLight,
        onBackground = onBackgroundLight,
        surface = surfaceLight,
        onSurface = onSurfaceLight,
        surfaceVariant = surfaceVariantLight,
        onSurfaceVariant = onSurfaceVariantLight,
        outline = outlineLight,
        outlineVariant = outlineVariantLight,
        scrim = scrimLight,
        inverseSurface = inverseSurfaceLight,
        inverseOnSurface = inverseOnSurfaceLight,
        inversePrimary = inversePrimaryLight,
        surfaceDim = surfaceDimLight,
        surfaceBright = surfaceBrightLight,
        surfaceContainerLowest = surfaceContainerLowestLight,
        surfaceContainerLow = surfaceContainerLowLight,
        surfaceContainer = surfaceContainerLight,
        surfaceContainerHigh = surfaceContainerHighLight,
        surfaceContainerHighest = surfaceContainerHighestLight
    )

    val darkColorScheme = darkColorScheme(
        primary = primaryDark,
        onPrimary = onPrimaryDark,
        primaryContainer = primaryContainerDark,
        onPrimaryContainer = onPrimaryContainerDark,
        secondary = secondaryDark,
        onSecondary = onSecondaryDark,
        secondaryContainer = secondaryContainerDark,
        onSecondaryContainer = onSecondaryContainerDark,
        tertiary = tertiaryDark,
        onTertiary = onTertiaryDark,
        tertiaryContainer = tertiaryContainerDark,
        onTertiaryContainer = onTertiaryContainerDark,
        error = errorDark,
        onError = onErrorDark,
        errorContainer = errorContainerDark,
        onErrorContainer = onErrorContainerDark,
        background = backgroundDark,
        onBackground = onBackgroundDark,
        surface = surfaceDark,
        onSurface = onSurfaceDark,
        surfaceVariant = surfaceVariantDark,
        onSurfaceVariant = onSurfaceVariantDark,
        outline = outlineDark,
        outlineVariant = outlineVariantDark,
        scrim = scrimDark,
        inverseSurface = inverseSurfaceDark,
        inverseOnSurface = inverseOnSurfaceDark,
        inversePrimary = inversePrimaryDark,
        surfaceDim = surfaceDimDark,
        surfaceBright = surfaceBrightDark,
        surfaceContainerLowest = surfaceContainerLowestDark,
        surfaceContainerLow = surfaceContainerLowDark,
        surfaceContainer = surfaceContainerDark,
        surfaceContainerHigh = surfaceContainerHighDark,
        surfaceContainerHighest = surfaceContainerHighestDark,
    )
}

object MD3ColorPalette_Yellow {

    val primaryLight = Color(0xFF6D5E0F)
    val onPrimaryLight = Color(0xFFFFFFFF)
    val primaryContainerLight = Color(0xFFF8E287)
    val onPrimaryContainerLight = Color(0xFF534600)
    val secondaryLight = Color(0xFF665E40)
    val onSecondaryLight = Color(0xFFFFFFFF)
    val secondaryContainerLight = Color(0xFFEEE2BC)
    val onSecondaryContainerLight = Color(0xFF4E472A)
    val tertiaryLight = Color(0xFF43664E)
    val onTertiaryLight = Color(0xFFFFFFFF)
    val tertiaryContainerLight = Color(0xFFC5ECCE)
    val onTertiaryContainerLight = Color(0xFF2C4E38)
    val errorLight = Color(0xFFBA1A1A)
    val onErrorLight = Color(0xFFFFFFFF)
    val errorContainerLight = Color(0xFFFFDAD6)
    val onErrorContainerLight = Color(0xFF93000A)
    val backgroundLight = Color(0xFFFFF9EE)
    val onBackgroundLight = Color(0xFF1E1B13)
    val surfaceLight = Color(0xFFFFF9EE)
    val onSurfaceLight = Color(0xFF1E1B13)
    val surfaceVariantLight = Color(0xFFEAE2D0)
    val onSurfaceVariantLight = Color(0xFF4B4739)
    val outlineLight = Color(0xFF7C7767)
    val outlineVariantLight = Color(0xFFCDC6B4)
    val scrimLight = Color(0xFF000000)
    val inverseSurfaceLight = Color(0xFF333027)
    val inverseOnSurfaceLight = Color(0xFFF7F0E2)
    val inversePrimaryLight = Color(0xFFDBC66E)
    val surfaceDimLight = Color(0xFFE0D9CC)
    val surfaceBrightLight = Color(0xFFFFF9EE)
    val surfaceContainerLowestLight = Color(0xFFFFFFFF)
    val surfaceContainerLowLight = Color(0xFFFAF3E5)
    val surfaceContainerLight = Color(0xFFF4EDDF)
    val surfaceContainerHighLight = Color(0xFFEEE8DA)
    val surfaceContainerHighestLight = Color(0xFFE8E2D4)

    val primaryLightMediumContrast = Color(0xFF403600)
    val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
    val primaryContainerLightMediumContrast = Color(0xFF7D6C1E)
    val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    val secondaryLightMediumContrast = Color(0xFF3C361B)
    val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
    val secondaryContainerLightMediumContrast = Color(0xFF756D4E)
    val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    val tertiaryLightMediumContrast = Color(0xFF1B3D28)
    val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
    val tertiaryContainerLightMediumContrast = Color(0xFF52755D)
    val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    val errorLightMediumContrast = Color(0xFF740006)
    val onErrorLightMediumContrast = Color(0xFFFFFFFF)
    val errorContainerLightMediumContrast = Color(0xFFCF2C27)
    val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
    val backgroundLightMediumContrast = Color(0xFFFFF9EE)
    val onBackgroundLightMediumContrast = Color(0xFF1E1B13)
    val surfaceLightMediumContrast = Color(0xFFFFF9EE)
    val onSurfaceLightMediumContrast = Color(0xFF131109)
    val surfaceVariantLightMediumContrast = Color(0xFFEAE2D0)
    val onSurfaceVariantLightMediumContrast = Color(0xFF3A3629)
    val outlineLightMediumContrast = Color(0xFF575244)
    val outlineVariantLightMediumContrast = Color(0xFF726D5E)
    val scrimLightMediumContrast = Color(0xFF000000)
    val inverseSurfaceLightMediumContrast = Color(0xFF333027)
    val inverseOnSurfaceLightMediumContrast = Color(0xFFF7F0E2)
    val inversePrimaryLightMediumContrast = Color(0xFFDBC66E)
    val surfaceDimLightMediumContrast = Color(0xFFCCC6B9)
    val surfaceBrightLightMediumContrast = Color(0xFFFFF9EE)
    val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
    val surfaceContainerLowLightMediumContrast = Color(0xFFFAF3E5)
    val surfaceContainerLightMediumContrast = Color(0xFFEEE8DA)
    val surfaceContainerHighLightMediumContrast = Color(0xFFE3DCCF)
    val surfaceContainerHighestLightMediumContrast = Color(0xFFD7D1C4)

    val primaryLightHighContrast = Color(0xFF352C00)
    val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
    val primaryContainerLightHighContrast = Color(0xFF564800)
    val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
    val secondaryLightHighContrast = Color(0xFF322C12)
    val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
    val secondaryContainerLightHighContrast = Color(0xFF50492D)
    val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
    val tertiaryLightHighContrast = Color(0xFF10321F)
    val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
    val tertiaryContainerLightHighContrast = Color(0xFF2E503A)
    val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
    val errorLightHighContrast = Color(0xFF600004)
    val onErrorLightHighContrast = Color(0xFFFFFFFF)
    val errorContainerLightHighContrast = Color(0xFF98000A)
    val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
    val backgroundLightHighContrast = Color(0xFFFFF9EE)
    val onBackgroundLightHighContrast = Color(0xFF1E1B13)
    val surfaceLightHighContrast = Color(0xFFFFF9EE)
    val onSurfaceLightHighContrast = Color(0xFF000000)
    val surfaceVariantLightHighContrast = Color(0xFFEAE2D0)
    val onSurfaceVariantLightHighContrast = Color(0xFF000000)
    val outlineLightHighContrast = Color(0xFF2F2C20)
    val outlineVariantLightHighContrast = Color(0xFF4D493B)
    val scrimLightHighContrast = Color(0xFF000000)
    val inverseSurfaceLightHighContrast = Color(0xFF333027)
    val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
    val inversePrimaryLightHighContrast = Color(0xFFDBC66E)
    val surfaceDimLightHighContrast = Color(0xFFBEB8AB)
    val surfaceBrightLightHighContrast = Color(0xFFFFF9EE)
    val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
    val surfaceContainerLowLightHighContrast = Color(0xFFF7F0E2)
    val surfaceContainerLightHighContrast = Color(0xFFE8E2D4)
    val surfaceContainerHighLightHighContrast = Color(0xFFDAD4C6)
    val surfaceContainerHighestLightHighContrast = Color(0xFFCCC6B9)

    val primaryDark = Color(0xFFDBC66E)
    val onPrimaryDark = Color(0xFF3A3000)
    val primaryContainerDark = Color(0xFF534600)
    val onPrimaryContainerDark = Color(0xFFF8E287)
    val secondaryDark = Color(0xFFD1C6A1)
    val onSecondaryDark = Color(0xFF363016)
    val secondaryContainerDark = Color(0xFF4E472A)
    val onSecondaryContainerDark = Color(0xFFEEE2BC)
    val tertiaryDark = Color(0xFFA9D0B3)
    val onTertiaryDark = Color(0xFF143723)
    val tertiaryContainerDark = Color(0xFF2C4E38)
    val onTertiaryContainerDark = Color(0xFFC5ECCE)
    val errorDark = Color(0xFFFFB4AB)
    val onErrorDark = Color(0xFF690005)
    val errorContainerDark = Color(0xFF93000A)
    val onErrorContainerDark = Color(0xFFFFDAD6)
    val backgroundDark = Color(0xFF15130B)
    val onBackgroundDark = Color(0xFFE8E2D4)
    val surfaceDark = Color(0xFF15130B)
    val onSurfaceDark = Color(0xFFE8E2D4)
    val surfaceVariantDark = Color(0xFF4B4739)
    val onSurfaceVariantDark = Color(0xFFCDC6B4)
    val outlineDark = Color(0xFF969080)
    val outlineVariantDark = Color(0xFF4B4739)
    val scrimDark = Color(0xFF000000)
    val inverseSurfaceDark = Color(0xFFE8E2D4)
    val inverseOnSurfaceDark = Color(0xFF333027)
    val inversePrimaryDark = Color(0xFF6D5E0F)
    val surfaceDimDark = Color(0xFF15130B)
    val surfaceBrightDark = Color(0xFF3C3930)
    val surfaceContainerLowestDark = Color(0xFF100E07)
    val surfaceContainerLowDark = Color(0xFF1E1B13)
    val surfaceContainerDark = Color(0xFF222017)
    val surfaceContainerHighDark = Color(0xFF2D2A21)
    val surfaceContainerHighestDark = Color(0xFF38352B)

    val primaryDarkMediumContrast = Color(0xFFF2DC82)
    val onPrimaryDarkMediumContrast = Color(0xFF2D2500)
    val primaryContainerDarkMediumContrast = Color(0xFFA3903F)
    val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
    val secondaryDarkMediumContrast = Color(0xFFE8DCB6)
    val onSecondaryDarkMediumContrast = Color(0xFF2B250C)
    val secondaryContainerDarkMediumContrast = Color(0xFF9A916F)
    val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
    val tertiaryDarkMediumContrast = Color(0xFFBFE6C8)
    val onTertiaryDarkMediumContrast = Color(0xFF082C18)
    val tertiaryContainerDarkMediumContrast = Color(0xFF75997F)
    val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
    val errorDarkMediumContrast = Color(0xFFFFD2CC)
    val onErrorDarkMediumContrast = Color(0xFF540003)
    val errorContainerDarkMediumContrast = Color(0xFFFF5449)
    val onErrorContainerDarkMediumContrast = Color(0xFF000000)
    val backgroundDarkMediumContrast = Color(0xFF15130B)
    val onBackgroundDarkMediumContrast = Color(0xFFE8E2D4)
    val surfaceDarkMediumContrast = Color(0xFF15130B)
    val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
    val surfaceVariantDarkMediumContrast = Color(0xFF4B4739)
    val onSurfaceVariantDarkMediumContrast = Color(0xFFE3DCCA)
    val outlineDarkMediumContrast = Color(0xFFB8B1A0)
    val outlineVariantDarkMediumContrast = Color(0xFF969080)
    val scrimDarkMediumContrast = Color(0xFF000000)
    val inverseSurfaceDarkMediumContrast = Color(0xFFE8E2D4)
    val inverseOnSurfaceDarkMediumContrast = Color(0xFF2D2A21)
    val inversePrimaryDarkMediumContrast = Color(0xFF554700)
    val surfaceDimDarkMediumContrast = Color(0xFF15130B)
    val surfaceBrightDarkMediumContrast = Color(0xFF48443A)
    val surfaceContainerLowestDarkMediumContrast = Color(0xFF090703)
    val surfaceContainerLowDarkMediumContrast = Color(0xFF201D15)
    val surfaceContainerDarkMediumContrast = Color(0xFF2A281F)
    val surfaceContainerHighDarkMediumContrast = Color(0xFF353229)
    val surfaceContainerHighestDarkMediumContrast = Color(0xFF413D34)

    val primaryDarkHighContrast = Color(0xFFFFF0BA)
    val onPrimaryDarkHighContrast = Color(0xFF000000)
    val primaryContainerDarkHighContrast = Color(0xFFD7C26B)
    val onPrimaryContainerDarkHighContrast = Color(0xFF0F0B00)
    val secondaryDarkHighContrast = Color(0xFFFCF0C9)
    val onSecondaryDarkHighContrast = Color(0xFF000000)
    val secondaryContainerDarkHighContrast = Color(0xFFCDC29E)
    val onSecondaryContainerDarkHighContrast = Color(0xFF0F0B00)
    val tertiaryDarkHighContrast = Color(0xFFD2FADB)
    val onTertiaryDarkHighContrast = Color(0xFF000000)
    val tertiaryContainerDarkHighContrast = Color(0xFFA5CCAF)
    val onTertiaryContainerDarkHighContrast = Color(0xFF000F05)
    val errorDarkHighContrast = Color(0xFFFFECE9)
    val onErrorDarkHighContrast = Color(0xFF000000)
    val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
    val onErrorContainerDarkHighContrast = Color(0xFF220001)
    val backgroundDarkHighContrast = Color(0xFF15130B)
    val onBackgroundDarkHighContrast = Color(0xFFE8E2D4)
    val surfaceDarkHighContrast = Color(0xFF15130B)
    val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
    val surfaceVariantDarkHighContrast = Color(0xFF4B4739)
    val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
    val outlineDarkHighContrast = Color(0xFFF7EFDD)
    val outlineVariantDarkHighContrast = Color(0xFFC9C2B1)
    val scrimDarkHighContrast = Color(0xFF000000)
    val inverseSurfaceDarkHighContrast = Color(0xFFE8E2D4)
    val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
    val inversePrimaryDarkHighContrast = Color(0xFF554700)
    val surfaceDimDarkHighContrast = Color(0xFF15130B)
    val surfaceBrightDarkHighContrast = Color(0xFF535046)
    val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
    val surfaceContainerLowDarkHighContrast = Color(0xFF222017)
    val surfaceContainerDarkHighContrast = Color(0xFF333027)
    val surfaceContainerHighDarkHighContrast = Color(0xFF3E3B32)
    val surfaceContainerHighestDarkHighContrast = Color(0xFF4A473D)

    val lightColorScheme = lightColorScheme(
        primary = primaryLight,
        onPrimary = onPrimaryLight,
        primaryContainer = primaryContainerLight,
        onPrimaryContainer = onPrimaryContainerLight,
        secondary = secondaryLight,
        onSecondary = onSecondaryLight,
        secondaryContainer = secondaryContainerLight,
        onSecondaryContainer = onSecondaryContainerLight,
        tertiary = tertiaryLight,
        onTertiary = onTertiaryLight,
        tertiaryContainer = tertiaryContainerLight,
        onTertiaryContainer = onTertiaryContainerLight,
        error = errorLight,
        onError = onErrorLight,
        errorContainer = errorContainerLight,
        onErrorContainer = onErrorContainerLight,
        background = backgroundLight,
        onBackground = onBackgroundLight,
        surface = surfaceLight,
        onSurface = onSurfaceLight,
        surfaceVariant = surfaceVariantLight,
        onSurfaceVariant = onSurfaceVariantLight,
        outline = outlineLight,
        outlineVariant = outlineVariantLight,
        scrim = scrimLight,
        inverseSurface = inverseSurfaceLight,
        inverseOnSurface = inverseOnSurfaceLight,
        inversePrimary = inversePrimaryLight,
        surfaceDim = surfaceDimLight,
        surfaceBright = surfaceBrightLight,
        surfaceContainerLowest = surfaceContainerLowestLight,
        surfaceContainerLow = surfaceContainerLowLight,
        surfaceContainer = surfaceContainerLight,
        surfaceContainerHigh = surfaceContainerHighLight,
        surfaceContainerHighest = surfaceContainerHighestLight
    )

    val darkColorScheme = darkColorScheme(
        primary = primaryDark,
        onPrimary = onPrimaryDark,
        primaryContainer = primaryContainerDark,
        onPrimaryContainer = onPrimaryContainerDark,
        secondary = secondaryDark,
        onSecondary = onSecondaryDark,
        secondaryContainer = secondaryContainerDark,
        onSecondaryContainer = onSecondaryContainerDark,
        tertiary = tertiaryDark,
        onTertiary = onTertiaryDark,
        tertiaryContainer = tertiaryContainerDark,
        onTertiaryContainer = onTertiaryContainerDark,
        error = errorDark,
        onError = onErrorDark,
        errorContainer = errorContainerDark,
        onErrorContainer = onErrorContainerDark,
        background = backgroundDark,
        onBackground = onBackgroundDark,
        surface = surfaceDark,
        onSurface = onSurfaceDark,
        surfaceVariant = surfaceVariantDark,
        onSurfaceVariant = onSurfaceVariantDark,
        outline = outlineDark,
        outlineVariant = outlineVariantDark,
        scrim = scrimDark,
        inverseSurface = inverseSurfaceDark,
        inverseOnSurface = inverseOnSurfaceDark,
        inversePrimary = inversePrimaryDark,
        surfaceDim = surfaceDimDark,
        surfaceBright = surfaceBrightDark,
        surfaceContainerLowest = surfaceContainerLowestDark,
        surfaceContainerLow = surfaceContainerLowDark,
        surfaceContainer = surfaceContainerDark,
        surfaceContainerHigh = surfaceContainerHighDark,
        surfaceContainerHighest = surfaceContainerHighestDark,
    )
}

object MD3ColorPalette_Purple {

    val primaryLight = Color(0xFF735187)
    val onPrimaryLight = Color(0xFFFFFFFF)
    val primaryContainerLight = Color(0xFFF4D9FF)
    val onPrimaryContainerLight = Color(0xFF5A396E)
    val secondaryLight = Color(0xFF68596E)
    val onSecondaryLight = Color(0xFFFFFFFF)
    val secondaryContainerLight = Color(0xFFEFDCF5)
    val onSecondaryContainerLight = Color(0xFF4F4255)
    val tertiaryLight = Color(0xFF815153)
    val onTertiaryLight = Color(0xFFFFFFFF)
    val tertiaryContainerLight = Color(0xFFFFDADA)
    val onTertiaryContainerLight = Color(0xFF663B3C)
    val errorLight = Color(0xFFBA1A1A)
    val onErrorLight = Color(0xFFFFFFFF)
    val errorContainerLight = Color(0xFFFFDAD6)
    val onErrorContainerLight = Color(0xFF93000A)
    val backgroundLight = Color(0xFFFFF7FC)
    val onBackgroundLight = Color(0xFF1E1A20)
    val surfaceLight = Color(0xFFFFF7FC)
    val onSurfaceLight = Color(0xFF1E1A20)
    val surfaceVariantLight = Color(0xFFEADFEA)
    val onSurfaceVariantLight = Color(0xFF4B454D)
    val outlineLight = Color(0xFF7D747E)
    val outlineVariantLight = Color(0xFFCEC3CE)
    val scrimLight = Color(0xFF000000)
    val inverseSurfaceLight = Color(0xFF332F35)
    val inverseOnSurfaceLight = Color(0xFFF7EEF6)
    val inversePrimaryLight = Color(0xFFE0B8F5)
    val surfaceDimLight = Color(0xFFE0D7DF)
    val surfaceBrightLight = Color(0xFFFFF7FC)
    val surfaceContainerLowestLight = Color(0xFFFFFFFF)
    val surfaceContainerLowLight = Color(0xFFFAF1F9)
    val surfaceContainerLight = Color(0xFFF4EBF3)
    val surfaceContainerHighLight = Color(0xFFEFE5ED)
    val surfaceContainerHighestLight = Color(0xFFE9E0E7)

    val primaryLightMediumContrast = Color(0xFF48285C)
    val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
    val primaryContainerLightMediumContrast = Color(0xFF825F97)
    val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    val secondaryLightMediumContrast = Color(0xFF3E3244)
    val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
    val secondaryContainerLightMediumContrast = Color(0xFF77687D)
    val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    val tertiaryLightMediumContrast = Color(0xFF532A2C)
    val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
    val tertiaryContainerLightMediumContrast = Color(0xFF926061)
    val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    val errorLightMediumContrast = Color(0xFF740006)
    val onErrorLightMediumContrast = Color(0xFFFFFFFF)
    val errorContainerLightMediumContrast = Color(0xFFCF2C27)
    val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
    val backgroundLightMediumContrast = Color(0xFFFFF7FC)
    val onBackgroundLightMediumContrast = Color(0xFF1E1A20)
    val surfaceLightMediumContrast = Color(0xFFFFF7FC)
    val onSurfaceLightMediumContrast = Color(0xFF131015)
    val surfaceVariantLightMediumContrast = Color(0xFFEADFEA)
    val onSurfaceVariantLightMediumContrast = Color(0xFF3A343C)
    val outlineLightMediumContrast = Color(0xFF575059)
    val outlineVariantLightMediumContrast = Color(0xFF726A74)
    val scrimLightMediumContrast = Color(0xFF000000)
    val inverseSurfaceLightMediumContrast = Color(0xFF332F35)
    val inverseOnSurfaceLightMediumContrast = Color(0xFFF7EEF6)
    val inversePrimaryLightMediumContrast = Color(0xFFE0B8F5)
    val surfaceDimLightMediumContrast = Color(0xFFCCC4CB)
    val surfaceBrightLightMediumContrast = Color(0xFFFFF7FC)
    val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
    val surfaceContainerLowLightMediumContrast = Color(0xFFFAF1F9)
    val surfaceContainerLightMediumContrast = Color(0xFFEFE5ED)
    val surfaceContainerHighLightMediumContrast = Color(0xFFE3DAE2)
    val surfaceContainerHighestLightMediumContrast = Color(0xFFD8CFD7)

    val primaryLightHighContrast = Color(0xFF3D1E51)
    val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
    val primaryContainerLightHighContrast = Color(0xFF5C3C70)
    val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
    val secondaryLightHighContrast = Color(0xFF34283A)
    val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
    val secondaryContainerLightHighContrast = Color(0xFF524458)
    val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
    val tertiaryLightHighContrast = Color(0xFF472123)
    val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
    val tertiaryContainerLightHighContrast = Color(0xFF693D3F)
    val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
    val errorLightHighContrast = Color(0xFF600004)
    val onErrorLightHighContrast = Color(0xFFFFFFFF)
    val errorContainerLightHighContrast = Color(0xFF98000A)
    val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
    val backgroundLightHighContrast = Color(0xFFFFF7FC)
    val onBackgroundLightHighContrast = Color(0xFF1E1A20)
    val surfaceLightHighContrast = Color(0xFFFFF7FC)
    val onSurfaceLightHighContrast = Color(0xFF000000)
    val surfaceVariantLightHighContrast = Color(0xFFEADFEA)
    val onSurfaceVariantLightHighContrast = Color(0xFF000000)
    val outlineLightHighContrast = Color(0xFF302A32)
    val outlineVariantLightHighContrast = Color(0xFF4E4750)
    val scrimLightHighContrast = Color(0xFF000000)
    val inverseSurfaceLightHighContrast = Color(0xFF332F35)
    val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
    val inversePrimaryLightHighContrast = Color(0xFFE0B8F5)
    val surfaceDimLightHighContrast = Color(0xFFBEB6BE)
    val surfaceBrightLightHighContrast = Color(0xFFFFF7FC)
    val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
    val surfaceContainerLowLightHighContrast = Color(0xFFF7EEF6)
    val surfaceContainerLightHighContrast = Color(0xFFE9E0E7)
    val surfaceContainerHighLightHighContrast = Color(0xFFDAD2D9)
    val surfaceContainerHighestLightHighContrast = Color(0xFFCCC4CB)

    val primaryDark = Color(0xFFE0B8F5)
    val onPrimaryDark = Color(0xFF422255)
    val primaryContainerDark = Color(0xFF5A396E)
    val onPrimaryContainerDark = Color(0xFFF4D9FF)
    val secondaryDark = Color(0xFFD3C1D8)
    val onSecondaryDark = Color(0xFF382C3E)
    val secondaryContainerDark = Color(0xFF4F4255)
    val onSecondaryContainerDark = Color(0xFFEFDCF5)
    val tertiaryDark = Color(0xFFF4B7B8)
    val onTertiaryDark = Color(0xFF4C2527)
    val tertiaryContainerDark = Color(0xFF663B3C)
    val onTertiaryContainerDark = Color(0xFFFFDADA)
    val errorDark = Color(0xFFFFB4AB)
    val onErrorDark = Color(0xFF690005)
    val errorContainerDark = Color(0xFF93000A)
    val onErrorContainerDark = Color(0xFFFFDAD6)
    val backgroundDark = Color(0xFF161217)
    val onBackgroundDark = Color(0xFFE9E0E7)
    val surfaceDark = Color(0xFF161217)
    val onSurfaceDark = Color(0xFFE9E0E7)
    val surfaceVariantDark = Color(0xFF4B454D)
    val onSurfaceVariantDark = Color(0xFFCEC3CE)
    val outlineDark = Color(0xFF978E98)
    val outlineVariantDark = Color(0xFF4B454D)
    val scrimDark = Color(0xFF000000)
    val inverseSurfaceDark = Color(0xFFE9E0E7)
    val inverseOnSurfaceDark = Color(0xFF332F35)
    val inversePrimaryDark = Color(0xFF735187)
    val surfaceDimDark = Color(0xFF161217)
    val surfaceBrightDark = Color(0xFF3C383D)
    val surfaceContainerLowestDark = Color(0xFF100D12)
    val surfaceContainerLowDark = Color(0xFF1E1A20)
    val surfaceContainerDark = Color(0xFF221E24)
    val surfaceContainerHighDark = Color(0xFF2D282E)
    val surfaceContainerHighestDark = Color(0xFF383339)

    val primaryDarkMediumContrast = Color(0xFFF1D1FF)
    val onPrimaryDarkMediumContrast = Color(0xFF36174A)
    val primaryContainerDarkMediumContrast = Color(0xFFA883BD)
    val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
    val secondaryDarkMediumContrast = Color(0xFFE9D6EE)
    val onSecondaryDarkMediumContrast = Color(0xFF2D2133)
    val secondaryContainerDarkMediumContrast = Color(0xFF9B8BA1)
    val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
    val tertiaryDarkMediumContrast = Color(0xFFFFD1D2)
    val onTertiaryDarkMediumContrast = Color(0xFF3F1A1D)
    val tertiaryContainerDarkMediumContrast = Color(0xFFB98384)
    val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
    val errorDarkMediumContrast = Color(0xFFFFD2CC)
    val onErrorDarkMediumContrast = Color(0xFF540003)
    val errorContainerDarkMediumContrast = Color(0xFFFF5449)
    val onErrorContainerDarkMediumContrast = Color(0xFF000000)
    val backgroundDarkMediumContrast = Color(0xFF161217)
    val onBackgroundDarkMediumContrast = Color(0xFFE9E0E7)
    val surfaceDarkMediumContrast = Color(0xFF161217)
    val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
    val surfaceVariantDarkMediumContrast = Color(0xFF4B454D)
    val onSurfaceVariantDarkMediumContrast = Color(0xFFE4D9E4)
    val outlineDarkMediumContrast = Color(0xFFB9AFB9)
    val outlineVariantDarkMediumContrast = Color(0xFF968E97)
    val scrimDarkMediumContrast = Color(0xFF000000)
    val inverseSurfaceDarkMediumContrast = Color(0xFFE9E0E7)
    val inverseOnSurfaceDarkMediumContrast = Color(0xFF2D292E)
    val inversePrimaryDarkMediumContrast = Color(0xFF5B3A6F)
    val surfaceDimDarkMediumContrast = Color(0xFF161217)
    val surfaceBrightDarkMediumContrast = Color(0xFF484349)
    val surfaceContainerLowestDarkMediumContrast = Color(0xFF09060B)
    val surfaceContainerLowDarkMediumContrast = Color(0xFF201C22)
    val surfaceContainerDarkMediumContrast = Color(0xFF2B262C)
    val surfaceContainerHighDarkMediumContrast = Color(0xFF363137)
    val surfaceContainerHighestDarkMediumContrast = Color(0xFF413C42)

    val primaryDarkHighContrast = Color(0xFFFBEBFF)
    val onPrimaryDarkHighContrast = Color(0xFF000000)
    val primaryContainerDarkHighContrast = Color(0xFFDCB4F1)
    val onPrimaryContainerDarkHighContrast = Color(0xFF170028)
    val secondaryDarkHighContrast = Color(0xFFFBEBFF)
    val onSecondaryDarkHighContrast = Color(0xFF000000)
    val secondaryContainerDarkHighContrast = Color(0xFFCFBDD4)
    val onSecondaryContainerDarkHighContrast = Color(0xFF110717)
    val tertiaryDarkHighContrast = Color(0xFFFFECEB)
    val onTertiaryDarkHighContrast = Color(0xFF000000)
    val tertiaryContainerDarkHighContrast = Color(0xFFF0B3B5)
    val onTertiaryContainerDarkHighContrast = Color(0xFF1E0305)
    val errorDarkHighContrast = Color(0xFFFFECE9)
    val onErrorDarkHighContrast = Color(0xFF000000)
    val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
    val onErrorContainerDarkHighContrast = Color(0xFF220001)
    val backgroundDarkHighContrast = Color(0xFF161217)
    val onBackgroundDarkHighContrast = Color(0xFFE9E0E7)
    val surfaceDarkHighContrast = Color(0xFF161217)
    val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
    val surfaceVariantDarkHighContrast = Color(0xFF4B454D)
    val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
    val outlineDarkHighContrast = Color(0xFFF8EDF8)
    val outlineVariantDarkHighContrast = Color(0xFFCABFCA)
    val scrimDarkHighContrast = Color(0xFF000000)
    val inverseSurfaceDarkHighContrast = Color(0xFFE9E0E7)
    val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
    val inversePrimaryDarkHighContrast = Color(0xFF5B3A6F)
    val surfaceDimDarkHighContrast = Color(0xFF161217)
    val surfaceBrightDarkHighContrast = Color(0xFF544E55)
    val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
    val surfaceContainerLowDarkHighContrast = Color(0xFF221E24)
    val surfaceContainerDarkHighContrast = Color(0xFF332F35)
    val surfaceContainerHighDarkHighContrast = Color(0xFF3F3A40)
    val surfaceContainerHighestDarkHighContrast = Color(0xFF4A454B)

    val lightColorScheme = lightColorScheme(
        primary = primaryLight,
        onPrimary = onPrimaryLight,
        primaryContainer = primaryContainerLight,
        onPrimaryContainer = onPrimaryContainerLight,
        secondary = secondaryLight,
        onSecondary = onSecondaryLight,
        secondaryContainer = secondaryContainerLight,
        onSecondaryContainer = onSecondaryContainerLight,
        tertiary = tertiaryLight,
        onTertiary = onTertiaryLight,
        tertiaryContainer = tertiaryContainerLight,
        onTertiaryContainer = onTertiaryContainerLight,
        error = errorLight,
        onError = onErrorLight,
        errorContainer = errorContainerLight,
        onErrorContainer = onErrorContainerLight,
        background = backgroundLight,
        onBackground = onBackgroundLight,
        surface = surfaceLight,
        onSurface = onSurfaceLight,
        surfaceVariant = surfaceVariantLight,
        onSurfaceVariant = onSurfaceVariantLight,
        outline = outlineLight,
        outlineVariant = outlineVariantLight,
        scrim = scrimLight,
        inverseSurface = inverseSurfaceLight,
        inverseOnSurface = inverseOnSurfaceLight,
        inversePrimary = inversePrimaryLight,
        surfaceDim = surfaceDimLight,
        surfaceBright = surfaceBrightLight,
        surfaceContainerLowest = surfaceContainerLowestLight,
        surfaceContainerLow = surfaceContainerLowLight,
        surfaceContainer = surfaceContainerLight,
        surfaceContainerHigh = surfaceContainerHighLight,
        surfaceContainerHighest = surfaceContainerHighestLight
    )

    val darkColorScheme = darkColorScheme(
        primary = primaryDark,
        onPrimary = onPrimaryDark,
        primaryContainer = primaryContainerDark,
        onPrimaryContainer = onPrimaryContainerDark,
        secondary = secondaryDark,
        onSecondary = onSecondaryDark,
        secondaryContainer = secondaryContainerDark,
        onSecondaryContainer = onSecondaryContainerDark,
        tertiary = tertiaryDark,
        onTertiary = onTertiaryDark,
        tertiaryContainer = tertiaryContainerDark,
        onTertiaryContainer = onTertiaryContainerDark,
        error = errorDark,
        onError = onErrorDark,
        errorContainer = errorContainerDark,
        onErrorContainer = onErrorContainerDark,
        background = backgroundDark,
        onBackground = onBackgroundDark,
        surface = surfaceDark,
        onSurface = onSurfaceDark,
        surfaceVariant = surfaceVariantDark,
        onSurfaceVariant = onSurfaceVariantDark,
        outline = outlineDark,
        outlineVariant = outlineVariantDark,
        scrim = scrimDark,
        inverseSurface = inverseSurfaceDark,
        inverseOnSurface = inverseOnSurfaceDark,
        inversePrimary = inversePrimaryDark,
        surfaceDim = surfaceDimDark,
        surfaceBright = surfaceBrightDark,
        surfaceContainerLowest = surfaceContainerLowestDark,
        surfaceContainerLow = surfaceContainerLowDark,
        surfaceContainer = surfaceContainerDark,
        surfaceContainerHigh = surfaceContainerHighDark,
        surfaceContainerHighest = surfaceContainerHighestDark,
    )
}



